// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageNameObject.proto

package com.bonree.brfs.common.proto;

public final class StorageNameProtos {
  private StorageNameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StorageNameRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string sessionId = 1;
    boolean hasSessionId();
    String getSessionId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional int32 ttl = 3;
    boolean hasTtl();
    int getTtl();
    
    // optional string description = 4;
    boolean hasDescription();
    String getDescription();
    
    // optional int32 replicas = 5;
    boolean hasReplicas();
    int getReplicas();
    
    // optional bool recoverFlag = 6;
    boolean hasRecoverFlag();
    boolean getRecoverFlag();
    
    // optional string user = 7;
    boolean hasUser();
    String getUser();
    
    // optional .brfs.proto.StorageNameRequest.StorageNameOptType storageNameOptType = 8;
    boolean hasStorageNameOptType();
    com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType getStorageNameOptType();
  }
  public static final class StorageNameRequest extends
      com.google.protobuf.GeneratedMessage
      implements StorageNameRequestOrBuilder {
    // Use StorageNameRequest.newBuilder() to construct.
    private StorageNameRequest(Builder builder) {
      super(builder);
    }
    private StorageNameRequest(boolean noInit) {}
    
    private static final StorageNameRequest defaultInstance;
    public static StorageNameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public StorageNameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameRequest_fieldAccessorTable;
    }
    
    public enum StorageNameOptType
        implements com.google.protobuf.ProtocolMessageEnum {
      CREATE(0, 0),
      UPDATE(1, 1),
      DELETE(2, 2),
      ;
      
      public static final int CREATE_VALUE = 0;
      public static final int UPDATE_VALUE = 1;
      public static final int DELETE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static StorageNameOptType valueOf(int value) {
        switch (value) {
          case 0: return CREATE;
          case 1: return UPDATE;
          case 2: return DELETE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<StorageNameOptType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StorageNameOptType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StorageNameOptType>() {
              public StorageNameOptType findValueByNumber(int number) {
                return StorageNameOptType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final StorageNameOptType[] VALUES = {
        CREATE, UPDATE, DELETE, 
      };
      
      public static StorageNameOptType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private StorageNameOptType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:brfs.proto.StorageNameRequest.StorageNameOptType)
    }
    
    private int bitField0_;
    // optional string sessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private java.lang.Object sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 ttl = 3;
    public static final int TTL_FIELD_NUMBER = 3;
    private int ttl_;
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getTtl() {
      return ttl_;
    }
    
    // optional string description = 4;
    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 replicas = 5;
    public static final int REPLICAS_FIELD_NUMBER = 5;
    private int replicas_;
    public boolean hasReplicas() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getReplicas() {
      return replicas_;
    }
    
    // optional bool recoverFlag = 6;
    public static final int RECOVERFLAG_FIELD_NUMBER = 6;
    private boolean recoverFlag_;
    public boolean hasRecoverFlag() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getRecoverFlag() {
      return recoverFlag_;
    }
    
    // optional string user = 7;
    public static final int USER_FIELD_NUMBER = 7;
    private java.lang.Object user_;
    public boolean hasUser() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          user_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .brfs.proto.StorageNameRequest.StorageNameOptType storageNameOptType = 8;
    public static final int STORAGENAMEOPTTYPE_FIELD_NUMBER = 8;
    private com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType storageNameOptType_;
    public boolean hasStorageNameOptType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType getStorageNameOptType() {
      return storageNameOptType_;
    }
    
    private void initFields() {
      sessionId_ = "";
      name_ = "";
      ttl_ = 0;
      description_ = "";
      replicas_ = 0;
      recoverFlag_ = false;
      user_ = "";
      storageNameOptType_ = com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType.CREATE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, ttl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, replicas_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, recoverFlag_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getUserBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, storageNameOptType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ttl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, replicas_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, recoverFlag_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUserBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, storageNameOptType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameRequest_fieldAccessorTable;
      }
      
      // Construct using com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ttl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        replicas_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        recoverFlag_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        storageNameOptType_ = com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType.CREATE;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.getDescriptor();
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest getDefaultInstanceForType() {
        return com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.getDefaultInstance();
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest build() {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest buildPartial() {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest result = new com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ttl_ = ttl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.replicas_ = replicas_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.recoverFlag_ = recoverFlag_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.storageNameOptType_ = storageNameOptType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest) {
          return mergeFrom((com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest other) {
        if (other == com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasReplicas()) {
          setReplicas(other.getReplicas());
        }
        if (other.hasRecoverFlag()) {
          setRecoverFlag(other.getRecoverFlag());
        }
        if (other.hasUser()) {
          setUser(other.getUser());
        }
        if (other.hasStorageNameOptType()) {
          setStorageNameOptType(other.getStorageNameOptType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ttl_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              description_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              replicas_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              recoverFlag_ = input.readBool();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              user_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType value = com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                storageNameOptType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string sessionId = 1;
      private java.lang.Object sessionId_ = "";
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      void setSessionId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional int32 ttl = 3;
      private int ttl_ ;
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTtl() {
        return ttl_;
      }
      public Builder setTtl(int value) {
        bitField0_ |= 0x00000004;
        ttl_ = value;
        onChanged();
        return this;
      }
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ttl_ = 0;
        onChanged();
        return this;
      }
      
      // optional string description = 4;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
      }
      
      // optional int32 replicas = 5;
      private int replicas_ ;
      public boolean hasReplicas() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getReplicas() {
        return replicas_;
      }
      public Builder setReplicas(int value) {
        bitField0_ |= 0x00000010;
        replicas_ = value;
        onChanged();
        return this;
      }
      public Builder clearReplicas() {
        bitField0_ = (bitField0_ & ~0x00000010);
        replicas_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool recoverFlag = 6;
      private boolean recoverFlag_ ;
      public boolean hasRecoverFlag() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getRecoverFlag() {
        return recoverFlag_;
      }
      public Builder setRecoverFlag(boolean value) {
        bitField0_ |= 0x00000020;
        recoverFlag_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecoverFlag() {
        bitField0_ = (bitField0_ & ~0x00000020);
        recoverFlag_ = false;
        onChanged();
        return this;
      }
      
      // optional string user = 7;
      private java.lang.Object user_ = "";
      public boolean hasUser() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        user_ = value;
        onChanged();
        return this;
      }
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000040);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      void setUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        user_ = value;
        onChanged();
      }
      
      // optional .brfs.proto.StorageNameRequest.StorageNameOptType storageNameOptType = 8;
      private com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType storageNameOptType_ = com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType.CREATE;
      public boolean hasStorageNameOptType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType getStorageNameOptType() {
        return storageNameOptType_;
      }
      public Builder setStorageNameOptType(com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        storageNameOptType_ = value;
        onChanged();
        return this;
      }
      public Builder clearStorageNameOptType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        storageNameOptType_ = com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.StorageNameOptType.CREATE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:brfs.proto.StorageNameRequest)
    }
    
    static {
      defaultInstance = new StorageNameRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:brfs.proto.StorageNameRequest)
  }
  
  public interface StorageNameResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string sessionId = 1;
    boolean hasSessionId();
    String getSessionId();
    
    // optional int32 returnCode = 2;
    boolean hasReturnCode();
    int getReturnCode();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
  }
  public static final class StorageNameResponse extends
      com.google.protobuf.GeneratedMessage
      implements StorageNameResponseOrBuilder {
    // Use StorageNameResponse.newBuilder() to construct.
    private StorageNameResponse(Builder builder) {
      super(builder);
    }
    private StorageNameResponse(boolean noInit) {}
    
    private static final StorageNameResponse defaultInstance;
    public static StorageNameResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public StorageNameResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string sessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private java.lang.Object sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 returnCode = 2;
    public static final int RETURNCODE_FIELD_NUMBER = 2;
    private int returnCode_;
    public boolean hasReturnCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getReturnCode() {
      return returnCode_;
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sessionId_ = "";
      returnCode_ = 0;
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, returnCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, returnCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bonree.brfs.common.proto.StorageNameProtos.internal_static_brfs_proto_StorageNameResponse_fieldAccessorTable;
      }
      
      // Construct using com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        returnCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.getDescriptor();
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse getDefaultInstanceForType() {
        return com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.getDefaultInstance();
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse build() {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse buildPartial() {
        com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse result = new com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.returnCode_ = returnCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse) {
          return mergeFrom((com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse other) {
        if (other == com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasReturnCode()) {
          setReturnCode(other.getReturnCode());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              returnCode_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string sessionId = 1;
      private java.lang.Object sessionId_ = "";
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      void setSessionId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
      }
      
      // optional int32 returnCode = 2;
      private int returnCode_ ;
      public boolean hasReturnCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getReturnCode() {
        return returnCode_;
      }
      public Builder setReturnCode(int value) {
        bitField0_ |= 0x00000002;
        returnCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearReturnCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        returnCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:brfs.proto.StorageNameResponse)
    }
    
    static {
      defaultInstance = new StorageNameResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:brfs.proto.StorageNameResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brfs_proto_StorageNameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brfs_proto_StorageNameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brfs_proto_StorageNameResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brfs_proto_StorageNameResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027StorageNameObject.proto\022\nbrfs.proto\"\225\002" +
      "\n\022StorageNameRequest\022\021\n\tsessionId\030\001 \001(\t\022" +
      "\014\n\004name\030\002 \001(\t\022\013\n\003ttl\030\003 \001(\005\022\023\n\013descriptio" +
      "n\030\004 \001(\t\022\020\n\010replicas\030\005 \001(\005\022\023\n\013recoverFlag" +
      "\030\006 \001(\010\022\014\n\004user\030\007 \001(\t\022M\n\022storageNameOptTy" +
      "pe\030\010 \001(\01621.brfs.proto.StorageNameRequest" +
      ".StorageNameOptType\"8\n\022StorageNameOptTyp" +
      "e\022\n\n\006CREATE\020\000\022\n\n\006UPDATE\020\001\022\n\n\006DELETE\020\002\"Q\n" +
      "\023StorageNameResponse\022\021\n\tsessionId\030\001 \001(\t\022" +
      "\022\n\nreturnCode\030\002 \001(\005\022\023\n\013description\030\003 \001(\t",
      "B4\n\034com.bonree.brfs.common.protoB\021Storag" +
      "eNameProtos\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_brfs_proto_StorageNameRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_brfs_proto_StorageNameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brfs_proto_StorageNameRequest_descriptor,
              new java.lang.String[] { "SessionId", "Name", "Ttl", "Description", "Replicas", "RecoverFlag", "User", "StorageNameOptType", },
              com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.class,
              com.bonree.brfs.common.proto.StorageNameProtos.StorageNameRequest.Builder.class);
          internal_static_brfs_proto_StorageNameResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_brfs_proto_StorageNameResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brfs_proto_StorageNameResponse_descriptor,
              new java.lang.String[] { "SessionId", "ReturnCode", "Description", },
              com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.class,
              com.bonree.brfs.common.proto.StorageNameProtos.StorageNameResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
